{"cert_user_id": "unique1o1@github", "next_topic_id": 2, "topic": [{"topic_id": 1604065456, "title": "FileServer Upnp mapping failed ", "body": "using `python zeronet.py` gets me this error:\n\n```- Starting ZeroNet...\n[19:36:21] - OpenSSL loaded, version: 01000208F\n[19:36:21] - Version: 0.4.1 r1510, Python 2.7.9 (default, Mar  1 2015, 12:57:24) \n[GCC 4.9.2], Gevent: 1.0.1\n[19:36:22] - Creating FileServer....\n[19:36:22] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > socket.py line 342\n[19:36:22] - Creating UiServer....\n[19:36:22] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[19:36:22] - Removing old SSL certs...\n[19:36:22] - Starting servers....\n[19:36:22] Ui.UiServer --------------------------------------\n[19:36:22] Ui.UiServer Web interface: http://127.0.0.1:43110/\n[19:36:22] Ui.UiServer --------------------------------------\n[19:36:22] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[19:36:23] FileServer Checking port 15441 using portchecker.co...\n[19:36:25] FileServer [BAD :(] Port closed: Port 15441 is closed.\n[19:36:25] FileServer Trying to open port using UpnpPunch...\n[19:36:25] FileServer Checking port 15441 using portchecker.co...\n[19:36:27] FileServer [BAD :(] Port closed: Port 15441 is closed.\n[19:36:27] FileServer Checking port 15441 using canyouseeme.org...\n[19:36:39] FileServer [BAD :(] Port closed: Error: I could not see your service on 110.34.10.195 on port (15441) Reason: Connection timed out\n[19:36:39] FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress\n\n```\n\nand nothing happens. \n```\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1473159780, "modified": 1496326319, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572", "source_type": "github"}], "next_comment_id": 9, "comment": {"1604065456_mirrored_unique1o1_github": [{"comment_id": 1, "body": "That doesn't loads anything\n", "added": 1473203431, "modified": 1473203431, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572#issuecomment-245154186", "source_type": "github"}, {"comment_id": 2, "body": "I don't have any firewall on my computer and i don't think my router supports UPNP. But i have manually forwarded the port 15441 from the router. But it still doesn't works\n", "added": 1474434229, "modified": 1474434229, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572#issuecomment-248540156", "source_type": "github"}, {"comment_id": 3, "body": "nope, i can't access any content . I tried this one \"http://127.0.0.1:43110/1PLAYgDQboKojowD3kwdb3CtWmWaokXvfp\" but it said _This site can\u2019t be reached_ \nand portchecker shows me the 15441 port is closed even though i have it forwarded from my router\n", "added": 1474435043, "modified": 1474435043, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572#issuecomment-248542975", "source_type": "github"}, {"comment_id": 4, "body": "yeah, i did that on my router's firewall and i don't think  Debian has any  default firewall enabled\n", "added": 1474435416, "modified": 1474435416, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572#issuecomment-248544390", "source_type": "github"}, {"comment_id": 5, "body": "I allowed 15441 using ufw and `ufw status verbose` shows me its now allowed. But still i get port closed using portchecker.\nI tried the ssh port too but  it's closed too\n", "added": 1474436108, "modified": 1474436108, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572#issuecomment-248546976", "source_type": "github"}, {"comment_id": 6, "body": "is it possible that my ISP might be blocking port forwarding?\n", "added": 1474437102, "modified": 1474437102, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572#issuecomment-248550596", "source_type": "github"}, {"comment_id": 7, "body": "well, i 'm at Home. Is it because of shared IP that my ISP is giving me\n", "added": 1474437426, "modified": 1474437426, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572#issuecomment-248551894", "source_type": "github"}, {"comment_id": 8, "body": "okay then.... thanks\n", "added": 1474437775, "modified": 1474437775, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/572#issuecomment-248553237", "source_type": "github"}]}}