{"cert_user_id": "wizardforcel@github", "next_topic_id": 2, "topic": [{"topic_id": 1604067745, "title": "AttributeError on sitePublish on Linux", "body": "```\r\n- Libsecpk256k1 loaded: CompiledLib in 0.028s\r\n- Version: 0.7.1 r4206, Python 3.7.3 (default, Mar 27 2019, 22:11:17) \r\n[GCC 7.3.0], Gevent: 1.4.0\r\nSiteManager Deleting orphan site from content.db: 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F\r\nSiteManager Deleting orphan site from content.db: 1DvxA4WP2jbBaZbTebV1RufMLhTTqDhVUQ\r\n- Loading site...\r\n- Unhandled exception: 'NoneType' object has no attribute 'settings'\r\nTraceback (most recent call last):\r\n  File \"/builds/wizardforcel/zeronet-uploader/ZeroNet-linux-dist-linux64/core/zeronet.py\", line 17, in main\r\n    main.start()\r\n  File \"/builds/wizardforcel/zeronet-uploader/ZeroNet-linux-dist-linux64/core/src/main.py\", line 537, in start\r\n    actions.call(config.action, action_kwargs)\r\n  File \"/builds/wizardforcel/zeronet-uploader/ZeroNet-linux-dist-linux64/core/src/main.py\", line 121, in call\r\n    back = func(**kwargs)\r\n  File \"/builds/wizardforcel/zeronet-uploader/ZeroNet-linux-dist-linux64/core/src/main.py\", line 381, in sitePublish\r\n    site.settings[\"serving\"] = True  # Serving the site even if its disabled\r\nAttributeError: 'NoneType' object has no attribute 'settings'\r\n```", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1578291806, "modified": 1578643477, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2387", "source_type": "github"}], "next_comment_id": 2, "comment": {"1604067745_mirrored_wizardforcel_github": [{"comment_id": 1, "body": "@Crypto-Anarchist @imachug \r\n\r\nThx. I will try to find out what is wrong.", "added": 1578574652, "modified": 1578574652, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2387#issuecomment-572625233", "source_type": "github"}]}}