{"cert_user_id": "nathantym@github", "next_comment_id": 8, "comment": {"1604064727_mirrored_thesoftwarejedi_github": [{"comment_id": 1, "body": "I just cloned the repo and started using this and I've been receiving the same error. I'll be looking into it, so please let me know if there's any new information on it.\n", "added": 1422231097, "modified": 1422231097, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2#issuecomment-71409907", "source_type": "github"}, {"comment_id": 2, "body": "`WebSocket error: KeyError: 'cmd' in UiWebsocket.py line 34 > UiWebsocket.py line 80`\n\nhttps://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/UiWebsocket.py#L80\n`cmd = req[\"cmd\"]`\n\nIt's probably trying to set that key that isn't there yet. \n\nEDIT: Looking into it further it looks like there's a point where the key does not exist in the request data and that's when it errors out.\n\n```\n[u'cmd', u'params', u'id']\n[u'cmd', u'params', u'id']\n[u'cmd', u'params', u'id']\n[u'cmd', u'params', u'id']\n[u'cmd', u'params', u'id']\n[u'cmd', u'params', u'id']\n[u'opt', u'id']\n[22:39:39] Site:1EU1tb..E4Vr WebSocket error: KeyError: 'cmd' in UiWebsocket.py line 34 > UiWebsocket.py line 81\n```\n", "added": 1422231988, "modified": 1422232878, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2#issuecomment-71410674", "source_type": "github"}], "1604064743_mirrored_HelloZeroNet_github": [{"comment_id": 3, "body": "The gevent queue is as understandable as a straight python implemented queue and it seems easy to use.\n\nhttp://www.gevent.org/gevent.queue.html\n\none example they use at the bottom:\n\n```\ndef worker():\n    while True:\n        item = q.get()\n        try:\n            do_work(item)\n        finally:\n            q.task_done()\n\nq = JoinableQueue()\nfor i in range(num_worker_threads):\n     gevent.spawn(worker)\n\nfor item in source():\n    q.put(item)\n\nq.join()  # block until all tasks are done\n```\n", "added": 1422442533, "modified": 1422442533, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/11#issuecomment-71837873", "source_type": "github"}], "1604064754_mirrored_HelloZeroNet_github": [{"comment_id": 4, "body": "This is the command for OSX. \n\n```\nosascript -e \"open location \\\"http://127.0.0.1:43110\\\"\"\n```\n", "added": 1422274094, "modified": 1422274140, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/17#issuecomment-71474480", "source_type": "github"}, {"comment_id": 5, "body": "@volker48 \n\nJust a suggestion and it can always be added later, but some people might want it opened in a specific browser, as well as some people saying this opens a browser other than the default. Maybe we can have this as an option or take in an arg (browser name) that would open it.\n\nHere's how a specified browser can be opened:\nhttps://docs.python.org/2/library/webbrowser.html#webbrowser.get\n", "added": 1422293374, "modified": 1422293374, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/17#issuecomment-71531990", "source_type": "github"}], "1604064770_mirrored_arthurlutz_github": [{"comment_id": 6, "body": "I had this error too, but the page loaded and I couldn't replicate it again, even after restarting. Do you know if this is replicable?\n", "added": 1422300160, "modified": 1422300160, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/35#issuecomment-71551141", "source_type": "github"}, {"comment_id": 7, "body": "We'll need to figure out why the wrapper_key from the top error wasn't found. However, the NameError itself is because wrapper_key is improperly spelled as wraper_key in the log. I put in a quick fix for the NameError.\n", "added": 1422373010, "modified": 1422373010, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/35#issuecomment-71701910", "source_type": "github"}]}, "next_topic_id": 4, "topic": [{"topic_id": 1604064771, "title": "fix for socket error issue", "body": "Fix for the error in issue #2:\n\n`WebSocket error: KeyError: 'cmd' in UiWebsocket.py line 34 > UiWebsocket.py line 80`\n\nThis is good practice for future coding and should probably be used with other similar variables currently in the code. However, this has fixed all of the errors I've been receiving on each page and I haven't seen any others.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1422297446, "modified": 1422299622, "source_link": "https://github.com/HelloZeroNet/ZeroNet/pull/37", "source_type": "github"}, {"topic_id": 1604064773, "title": "Y wrapperbug", "body": "There was a typo in which was attempting to log out the wrapper_key, but instead it was spelled \"wraper_key\".\n\nThe NameError in issue #35 is fixed by this:\n\n```\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/gevent/pywsgi.py\", line 508, in handle_one_response\n    self.run_application()\n  File \"/home/arthur/local/ZeroNet/src/Ui/UiServer.py\", line 21, in run_application\n    self.ws_handler.run_application()\n  File \"/home/arthur/local/ZeroNet/src/lib/geventwebsocket/handler.py\", line 81, in run_application\n    self.run_websocket()\n  File \"/home/arthur/local/ZeroNet/src/lib/geventwebsocket/handler.py\", line 57, in run_websocket\n    self.application(self.environ, lambda s, h: [])\n  File \"/home/arthur/local/ZeroNet/src/Ui/UiServer.py\", line 49, in handleRequest\n    return self.ui_request.route(path)\n  File \"/home/arthur/local/ZeroNet/src/Ui/UiRequest.py\", line 41, in route\n    return self.actionWebsocket()\n  File \"/home/arthur/local/ZeroNet/src/Ui/UiRequest.py\", line 239, in actionWebsocket\n    self.log.error(\"Wrapper key not found: %s\" % wraper_key)\nNameError: global name 'wraper_key' is not defined\n```\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1422372757, "modified": 1422373199, "source_link": "https://github.com/HelloZeroNet/ZeroNet/pull/38", "source_type": "github"}, {"topic_id": 1604064782, "title": "Prompt user to download sites", "body": "Creating an issue about an enhancement discussed in irc that I'm working on.\n\nCurrently there are some security issues in regards to downloading sites. A good implementation would be to prompt a user prior to downloading a site in which would output metadata such as the site description and directory size, along with an accept or decline. Among the initial download, there is also no prompt to accept or decline the update of a site being published that grows in size. \n\nSuggestions or enhancements to such an idea are of course welcome.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1422547670, "modified": 1423921645, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/44", "source_type": "github"}]}