{"cert_user_id": "yurkobb@github", "next_topic_id": 2, "topic": [{"topic_id": 1604066574, "title": "AttributeError on sitePublish", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: ZeroNet 0.6.2 r3477 (git commit 7bff5f562c42a4a5f73e104c0f767c1413064aa6)\r\n  * Operating system: Fedora 28\r\n  * Web browser: command line command\r\n  * Tor status: always\r\n  * Opened port: no\r\n  * Special configuration: ____\r\n\r\n### Step 2: Describe the problem:\r\nRunning `./zeronet.py sitePublish ADDRESS` throws AttributeError exception multiple times (see below).\r\n\r\n#### Steps to reproduce:\r\n\r\n  1. run sitePublish ADDRESS\r\n\r\n#### Observed Results:\r\n    - Starting ZeroNet...\r\n    - OpenSSL loaded, version: 0100020FF\r\n    - Patching sockets to tor socks proxy: 127.0.0.1:9050\r\n    - Version: 0.6.2 r3477, Python 2.7.15 (default, May 16 2018, 17:50:09) \r\n    [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)], Gevent: 1.2.2\r\n    - Loading site...\r\n    - Can't connect to local websocket client: 0x01: General SOCKS server failure\r\n    - Creating FileServer....\r\n    TorManager Connecting to Tor Controller 127.0.0.1:9051\r\n    ConnServer Checking port 15441 using portchecker.co...\r\n    - Unhandled exception\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib64/python2.7/site-packages/gevent/greenlet.py\", line 536, in run\r\n        result = self._run(*self.args, **self.kwargs)\r\n      File \"/home/zeronet/ZeroNet/src/File/FileServer.py\", line 255, in checkSite\r\n        site.announce(mode=\"startup\")  # Announce site to tracker\r\n      File \"/home/zeronet/ZeroNet/src/Site/Site.py\", line 777, in announce\r\n        self.announcer.announce(*args, **kwargs)\r\n      File \"plugins/AnnounceLocal/AnnounceLocalPlugin.py\", line 13, in announce\r\n        local_announcer = self.site.connection_server.local_announcer\r\n    AttributeError: 'ConnectionServer' object has no attribute 'local_announcer'\r\n\r\n[...]\r\n\r\n\r\n#### Expected Results:\r\n\r\nNo exceptions taking place.", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1529568009, "modified": 1529664688, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1459", "source_type": "github"}], "next_comment_id": 2, "comment": {"1604066574_mirrored_yurkobb_github": [{"comment_id": 1, "body": "I confirm the fix is valid in my environment.", "added": 1529654059, "modified": 1529654059, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1459#issuecomment-399404281", "source_type": "github"}]}}