{"cert_user_id": "SiNaPsEr0x@github", "next_comment_id": 8, "comment": {"1604065398_mirrored_brunoais_github": [{"comment_id": 1, "body": "on macos error from latest update... dont connect to tor... remaining in \r\n4] DEBUG    TorManager > PROTOCOLINFO\r\n[2018-01-04 11:18:15,744] DEBUG    TorManager < 250-PROTOCOLINFO 1\r\n250-AUTH METHODS=HASHEDPASSWORD\r\n250-VERSION Tor=\"0.3.1.9\"\r\n250 OK\r\n[2018-01-04 11:18:15,745] DEBUG    TorManager > AUTHENTICATE\r\n", "added": 1515050605, "modified": 1515050605, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/526#issuecomment-355247488", "source_type": "github"}], "1604065853_mirrored_virl_github": [{"comment_id": 2, "body": "or appdb for ipa...", "added": 1581248717, "modified": 1581248717, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/891#issuecomment-583853169", "source_type": "github"}], "1604066279_mirrored_minikr_github": [{"comment_id": 3, "body": "same problem with last update... please fix", "added": 1515596397, "modified": 1515596397, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1228#issuecomment-356684584", "source_type": "github"}], "1604067111_mirrored_SiNaPsEr0x_github": [{"comment_id": 4, "body": "I'll try and let you know but on Mac I overwrite servssl with OpenSSL on BREW.. before read you thanks", "added": 1549033854, "modified": 1549034308, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1884#issuecomment-459814884", "source_type": "github"}, {"comment_id": 5, "body": "on version MAC there is package with python (INCLUSE) obsolete... this is the problem", "added": 1549381595, "modified": 1549381595, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1884#issuecomment-460756113", "source_type": "github"}, {"comment_id": 6, "body": "<img width=\"1036\" alt=\"image\" src=\"https://user-images.githubusercontent.com/5438823/52297394-ecfbfa00-2980-11e9-89b9-1cd4137c036f.png\">\r\n", "added": 1549382543, "modified": 1549382543, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1884#issuecomment-460761825", "source_type": "github"}, {"comment_id": 7, "body": "I fix with download unix version from [and:](url\r\nhttps://github.com/HelloZeroNet/ZeroNet/archive/master.zip)\r\nI've completed the first three steps, the above is what happens when I try to complete the last step.\r\nInstall Homebrew\r\nbrew install python\r\npip install gevent msgpack-python\r\nDownload, Unpack, run python2 zeronet.py (from the other version is updated to python3)", "added": 1549713725, "modified": 1549713725, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1884#issuecomment-462051419", "source_type": "github"}]}, "next_topic_id": 2, "topic": [{"topic_id": 1604067111, "title": "bug SSL update", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 0.6.4 rev3703\r\n * Operating system: macOS 10.14.3\r\n  * Web browser: firefox or safari\r\n  * Tor status: /always/\r\n  * Opened port: no\r\n  * Special configuration: ____\r\n\r\n### Step 2: Describe the problem:\r\n```\r\nDownloading from: https://github.com/HelloZeroNet/ZeroNet/archive/master.zip Error downloading update from https://github.com/HelloZeroNet/ZeroNet/archive/master.zip: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)\r\nDownloading from: https://gitlab.com/HelloZeroNet/ZeroNet/repository/archive.zip?ref=master Error downloading update from https://gitlab.com/HelloZeroNet/ZeroNet/repository/archive.zip?ref=master: EOF occurred in violation of protocol (_ssl.c:661)\r\nDownloading from: https://try.gogs.io/ZeroNet/ZeroNet/archive/master.zip Error downloading update from https://try.gogs.io/ZeroNet/ZeroNet/archive/master.zip: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)\r\nUpdate error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)\r\n```\r\n#### Steps to reproduce:\r\n\r\nupdating problem with sslv1\r\n\r\n\r\nbut on update manually this error:\r\n\r\n```\r\nSiNaPsE at null in /Applications/ZeroNet.app/Contents/Resources/core\r\n$ python2 update.py \r\nUpdate site path: /Users/SiNaPsE/Library/Application Support/ZeroNet/data/1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp, bad_files: 0\r\nDownloading from: https://github.com/HelloZeroNet/ZeroNet/archive/master.zip . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Downloaded.\r\nPlugins enabled: ['Sidebar', 'ContentFilter', 'Bigfile', 'MergerSite', 'CryptMessage', 'Chart', 'Trayicon', 'FilePack', 'OptionalManager', 'UiConfig', 'TranslateSite', 'PeerDb', 'AnnounceLocal', 'Cors', 'AnnounceShare', 'Stats', 'Zeroname', 'AnnounceZero', 'Newsfeed'] disabled: ['DonationMessage', 'Dnschain', 'Zeroname-local', 'StemPort', 'UiPassword', 'Bootstrapper', 'Multiuser']\r\nExtracting to /Applications/ZeroNet.app/Contents/Resources/core... . . . . . . . . . . . . . . . . . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Done.\r\nPress enter to exit\r\n\r\nSiNaPsE at null in /Applications/ZeroNet.app/Contents/Resources/core\r\n$ /Applications/ZeroNet.app/Contents/MacOS/ZeroNet \r\n- Starting ZeroNet...\r\nERROR:root:Unhandled exception: signal only works in main thread\r\nTraceback (most recent call last):\r\n  File \"/Applications/ZeroNet.app/Contents/Resources/core/zeronet.py\", line 16, in main\r\nValueError: signal only works in main thread\r\nException in thread Thread-1:\r\nTraceback (most recent call last):\r\n  File \"threading.pyo\", line 801, in __bootstrap_inner\r\n  File \"threading.pyo\", line 754, in run\r\n  File \"/Applications/ZeroNet.app/Contents/Resources/boot.py\", line 157, in main\r\n  File \"/Applications/ZeroNet.app/Contents/Resources/core/zeronet.py\", line 56, in main\r\nImportError: No module named Config\r\n\r\n^CTraceback (most recent call last):\r\n  File \"/Applications/ZeroNet.app/Contents/Resources/__boot__.py\", line 81, in <module>\r\n    _run()\r\n  File \"/Applications/ZeroNet.app/Contents/Resources/__boot__.py\", line 66, in _run\r\n    exec(compile(source, path, 'exec'), globals(), globals())\r\n  File \"/Applications/ZeroNet.app/Contents/Resources/boot.py\", line 179, in <module>\r\n    gui()\r\n  File \"/Applications/ZeroNet.app/Contents/Resources/boot.py\", line 106, in gui\r\n    time.sleep(0.1)\r\nKeyboardInterrupt\r\n2019-02-01 16:11:58.506 ZeroNet[26769:266104] ZeroNet Error\r\n2019-02-01 16:11:58.506 ZeroNet[26769:266104] ZeroNet Error\r\n\r\nSiNaPsE at null in /Applications/ZeroNet.app/Contents/Resources/core\r\n$ \r\n```\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1549022933, "modified": 1549719811, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1884", "source_type": "github"}]}