{"cert_user_id": "n17r4m@github", "next_topic_id": 2, "topic": [{"topic_id": 1604064895, "title": "content.json download failed", "body": "Hey, on recommendation from a buddy, I've given ZeroNet a go, and am running into a problem with first launch.\n\nI'm on Ubuntu 15.04, and I've followed the instructions for a debian install.\n- sudo apt-get install msgpack-python python-gevent\n- wget https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz\n- tar xvpfz master.tar.gz- \n- cd ZeroNet-master\n- python zeronet.py\n- http://127.0.0.1:43110/ \n\nUnfortunately, on opening up the browser (I have tried restarting the server a few times now + browser refreshes) I get the spinning red box and then...\nConnecting... \nPeers found: 25 \nPeers found: 25 \nPeers found: 25 \ncontent.json download failed\n\nLog is\n\nStarting ZeroNet...\n[16:43:40] - Version: 0.3.1 r267, Python 2.7.9 (default, Apr 2 2015, 15:33:21)\n[GCC 4.9.2], Gevent: 1.0.1\n[16:43:40] - OpenSSL loaded, version: 01000106F\n[16:43:40] - Creating UiServer....\n[16:43:40] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[16:43:41] - Removing old SSL certs...\n[16:43:41] - Creating FileServer....\n[16:43:41] - Starting servers....\n[16:43:41] Ui.UiServer --------------------------------------\n[16:43:41] Ui.UiServer Web interface: http://127.0.0.1:43110/\n[16:43:41] Ui.UiServer --------------------------------------\n[16:43:42] FileServer Checking port 15441 using portchecker.co...\n[16:43:43] FileServer [BAD :(] Port closed: Port 15441 is closed.\n[16:43:43] FileServer Checking port 15441 using canyouseeme.org...\n[16:43:47] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n[16:43:51] FileServer [BAD :(] Port closed: Error: I could not see your service on 108.181.97.212 on port (15441) Reason: Connection timed out\n[16:43:51] FileServer Trying to open port using UpnpPunch...\n[16:43:53] FileServer Checking port 15441 using portchecker.co...\n[16:43:53] FileServer [OK :)] Port open: Port 15441 is open.\n[16:43:53] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n[16:43:55] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[16:44:48] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n[16:44:48] - UiWSGIHandler error: error: [Errno 32] Broken pipe in UiServer.py line 36 > pywsgi.py line 495 > pywsgi.py line 486 > pywsgi.py line 376 > pywsgi.py line 369 > pywsgi.py line 355 > socket.py line 458 > socket.py line 435\n[16:44:48] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n[16:44:48] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n[16:44:48] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n[16:46:21] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n[16:46:57] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[16:46:57] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[16:49:42] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n\nAs mentioned.. problem persists across restarts..\n\nStarting ZeroNet...\n[16:57:52] - Version: 0.3.1 r267, Python 2.7.9 (default, Apr 2 2015, 15:33:21)\n[GCC 4.9.2], Gevent: 1.0.1\n[16:57:52] - OpenSSL loaded, version: 01000106F\n[16:57:52] - Creating UiServer....\n[16:57:52] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[16:57:52] - Removing old SSL certs...\n[16:57:52] - Creating FileServer....\n[16:57:53] - Starting servers....\n[16:57:53] Ui.UiServer --------------------------------------\n[16:57:53] Ui.UiServer Web interface: http://127.0.0.1:43110/\n[16:57:53] Ui.UiServer --------------------------------------\n[16:57:54] FileServer Checking port 15441 using portchecker.co...\n[16:57:54] FileServer [OK :)] Port open: Port 15441 is open.\n[16:57:54] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[16:57:57] Ui.UiServer Wrapper key not found: oIWbsI6D05mk\n[16:59:09] Site:1EU1tb..E4Vr Content.json not exist: data/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr/content.json\n[16:59:11] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n[16:59:11] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json\n\n---\n\nSo, am I doing something wrong?\n\ndefault python is 2.7.9\npython 3.4 is also installed and available\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1436215461, "modified": 1583929649, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/134", "source_type": "github"}], "next_comment_id": 6, "comment": {"1604064895_mirrored_n17r4m_github": [{"comment_id": 1, "body": "Sure thing. Here is a slice from the log. \n\n[REDACTED]\n\nAt a glance, there are two bad things happening... \n 'SSLContext' is not defined in Connection.py line 124\nand\n Connect error: Exception: Connection event return error in ConnectionServer.py line\n 129\n\nPardons for any exposed IP addresses...\n\nRunning the command as given (no encrypt, no ssl) lets me access the front page, and from there it seems as though I can access the network! I was able to visit some sites, although many failed. ZeroBoard seemed to be working fine.\n", "added": 1436219224, "modified": 1436220538, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/134#issuecomment-119036359", "source_type": "github"}, {"comment_id": 2, "body": "Hmm, very odd. Seems to be working now?\n\nMaybe because of:\n[19:09:12] - OpenSSL load failed: Disabled by config, falling back to slow bitcoin verify\n?\n\nStarting ZeroNet...\n[19:09:12] - Version: 0.3.1 r267, Python 2.7.9 (default, Apr  2 2015, 15:33:21) \n[GCC 4.9.2], Gevent: 1.0.1\n[19:09:12] - OpenSSL load failed: Disabled by config, falling back to slow bitcoin verify\n[19:09:12] - Creating UiServer....\n[19:09:12] - Removing old SSL certs...\n[19:09:12] - Creating FileServer....\n[19:09:12] - Starting servers....\n[19:09:12] Ui.UiServer --------------------------------------\n[19:09:12] Ui.UiServer Web interface: http://127.0.0.1:43110/\n[19:09:12] Ui.UiServer --------------------------------------\n[19:09:13] FileServer Checking port 15441 using portchecker.co...\n[19:09:13] FileServer [OK :)] Port open: Port 15441 is open.\n[19:09:31] Site:1Hcu2r..rvA7 index.html file size does not match 8530 <> 8598, Hash: False\n[19:09:31] Site:1Hcu2r..rvA7 index.html file size does not match 8530 <> 8598, Hash: False\n", "added": 1436220667, "modified": 1436220681, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/134#issuecomment-119039628", "source_type": "github"}, {"comment_id": 3, "body": "$ openssl version\nOpenSSL 1.0.1f 6 Jan 2014\n", "added": 1436221929, "modified": 1436221929, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/134#issuecomment-119041939", "source_type": "github"}, {"comment_id": 4, "body": "Unless I am mistaken, Ubuntu has backported fixes from newer versions, hopefully making it not vulnerable? \n\nOpenSSL 1.0.1f 6 Jan 2014\nbuilt on: Thu Jun 11 15:30:15 UTC 2015\n\nI tried the Lekensteyn pacemaker heartbleed check tool, and it declared:\n\"Did not receive heartbeat response! Timeout while waiting for bytes\nPossibly not vulnerable\"\n", "added": 1436273029, "modified": 1436273029, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/134#issuecomment-119243438", "source_type": "github"}, {"comment_id": 5, "body": "Confirmed fixed - I just cleared off the old version, grabbed a fresh checkout of master, and booted it up with no problems. Home page resolved in about 2.5 seconds. Can browse about and visit pages. Thanks!\n", "added": 1436291889, "modified": 1436291889, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/134#issuecomment-119337890", "source_type": "github"}]}}